# Use specify Ubuntu version image as the base

# Update APT

# Upgrade all existing packages

# Install python3 and pip, then clean up in a single RUN command

# Set the working directory inside the container

# Copy the api file into the container

# Copy the project_files directory into the container

# Use pip to install flask and flask-cors

# Expose port for flask

# Run flask on exposed port
